# vi:set ft=python:
SConscript('../../SCommon')
Import('SCommonEnvironment')
env_t=SCommonEnvironment()

env=env_t.Clone()

# We will build it in this one instance
env.ApplySConscript(env.Root('nx.scons'))
# and use it, too
env.UseSConscript(env.Root('nx.scons'))

if env['cross'] == 'win':
  env.UseSystemLibrary(['shlwapi'],shared=True)


env.Program('working', source=['main.cc'])
